# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: realms.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='realms.proto',
  package='swarming.config',
  syntax='proto3',
  serialized_options=_b('Z3go.chromium.org/luci/swarming/proto/config;configpb'),
  serialized_pb=_b('\n\x0crealms.proto\x12\x0fswarming.config*\xaa\x01\n\x0fRealmPermission\x12 \n\x1cREALM_PERMISSION_UNSPECIFIED\x10\x00\x12&\n\"REALM_PERMISSION_POOLS_CREATE_TASK\x10\x01\x12*\n&REALM_PERMISSION_TASKS_CREATE_IN_REALM\x10\x02\x12!\n\x1dREALM_PERMISSION_TASKS_RUN_AS\x10\x03\x42\x35Z3go.chromium.org/luci/swarming/proto/config;configpbb\x06proto3')
)

_REALMPERMISSION = _descriptor.EnumDescriptor(
  name='RealmPermission',
  full_name='swarming.config.RealmPermission',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='REALM_PERMISSION_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REALM_PERMISSION_POOLS_CREATE_TASK', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REALM_PERMISSION_TASKS_CREATE_IN_REALM', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REALM_PERMISSION_TASKS_RUN_AS', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=34,
  serialized_end=204,
)
_sym_db.RegisterEnumDescriptor(_REALMPERMISSION)

RealmPermission = enum_type_wrapper.EnumTypeWrapper(_REALMPERMISSION)
REALM_PERMISSION_UNSPECIFIED = 0
REALM_PERMISSION_POOLS_CREATE_TASK = 1
REALM_PERMISSION_TASKS_CREATE_IN_REALM = 2
REALM_PERMISSION_TASKS_RUN_AS = 3


DESCRIPTOR.enum_types_by_name['RealmPermission'] = _REALMPERMISSION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
