# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='config.proto',
  package='machine_provider',
  serialized_pb='\n\x0c\x63onfig.proto\x12\x10machine_provider\"+\n\x0bSettingsCfg\x12\x1c\n\x14\x65nable_ts_monitoring\x18\x01 \x01(\x08')




_SETTINGSCFG = _descriptor.Descriptor(
  name='SettingsCfg',
  full_name='machine_provider.SettingsCfg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='enable_ts_monitoring', full_name='machine_provider.SettingsCfg.enable_ts_monitoring', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=34,
  serialized_end=77,
)

DESCRIPTOR.message_types_by_name['SettingsCfg'] = _SETTINGSCFG

class SettingsCfg(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SETTINGSCFG

  # @@protoc_insertion_point(class_scope:machine_provider.SettingsCfg)


# @@protoc_insertion_point(module_scope)
