# Warning: this file has to be kept in sync with ../../services/isolate/app.yaml
# and module-backend.yaml.

application: isolateserver-dev
module: default
version: go-test
runtime: go
api_version: go1

automatic_scaling:
  min_idle_instances: 2
  min_pending_latency: 50ms
  max_pending_latency: 250ms

handlers:
- url: /internal.*
  script: _go_app
  secure: always
  login: admin

- url: /restricted.*
  script: _go_app
  secure: always
  login: admin

- url: /(.+)\.(css|gif|ico|js)
  static_files: static/\1.\2
  upload: static/(.+)\.(css|gif|ico|js)
  secure: always

- url: /.*
  script: _go_app
  secure: always

inbound_services:
- warmup

skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?\..*
- ^tests.*
- ^tools.*
- ^(.*/)?.*\.orig
- ^(.*/)?.*\.rej
- ^(.*/)?.*\.py
- ^[A-Z]+
- ^[A-Z]+\.[a-z]+
