# Packages and builds the current folder for deployment to
# the dev environment.
# See go/luci-config-deploy for further information.
steps:
- name: gcr.io/chrome-infra-spinnaker/base
  args: ['make', 'external_deps']
- name: gcr.io/chrome-infra-spinnaker/tar
  args: ['cf', '$BUILD_ID.tar','.']
artifacts:
  objects:
    location: 'gs://chrome-infra-builds/luci-config/dev'
    paths: ['$BUILD_ID.tar']
