# Generated by the pRPC protocol buffer compiler plugin.  DO NOT EDIT!
# source: service.proto

from google.protobuf import descriptor_pb2


DiscoveryServiceDescription = {
  'descriptor': descriptor_pb2.ServiceDescriptorProto(),
  'package': 'discovery',
  'file': u'service.proto',
}
DiscoveryServiceDescription['descriptor'].ParseFromString('0a09446973636f76657279123a0a084465736372696265120f2e646973636f766572792e566f69641a1b2e646973636f766572792e4465736372696265526573706f6e73652200'.decode('hex'))
