# Generated by the pRPC protocol buffer compiler plugin.  DO NOT EDIT!
# source: test.proto

import base64
import zlib

from google.protobuf import descriptor_pb2

# Includes description of the test.proto and all of its transitive
# dependencies. Includes source code info.
FILE_DESCRIPTOR_SET = descriptor_pb2.FileDescriptorSet()
FILE_DESCRIPTOR_SET.ParseFromString(zlib.decompress(base64.b64decode(
    'eJylV09z29YRN0jZYZ5kG2I8GVVO7DVjV3JCU46UaVp7pjMgCUlwKZIFQKvq9GAQfKRQkwALgH'
    'I1mXyBfodeculMO9Pv0Jke+z167LWHHvrbB5CCnbo9lBfu27d/frtv3+6D+P1NIVKZpI15HKVR'
    'dY3p7buTKJpM5Z7iDRfjPTmbp5eZSO2uWD8KLqQtf7OAbHVDaLMtjbTdsq3Nap+IDdd7jc1kHo'
    'WJ5N3Xy93XtYZYN/3zaKl6X2ix2lzf32woEAXDthbXPhcbmXxubVtU4pyGXnn3Q3u13v9OE2su'
    'Wz0Qa2ym+n2T2x83ssAay8AaJgdWu1b9CsrAXX2PxHY1M1aMDVp7Yo3xLV0VYlsqFOHXrr34gx'
    'AVvaJf0x/rmvh7qbKhFtX9P2vUiuaXcTA5T2nXf0z7T7/8mtxzSZ1ByyJjkZ5HcdIgYzolJZQQ'
    'ApfxhRw1BA0SSdGY0vMgoSRaxL4kPxpJwnISXcg4lCNahCMZQ0SSMfd8Nhz4EqDq9FLGSRCFtN'
    '94KiDgpeR7IQ0ljSMoURAqrY7VMruOSeMAyRH7f9KADvZ5SSM5DkKZkAe3sxlMqeT50ZTSiODL'
    'f01v2K7np3DEchMcSigomM3hPAq9lBEiHuV6FBFs5EIcpwoJcR5GMcnferP5FLCDFU4ojmh4CS'
    'VJ3nxO3sQLwgTuwgjI4wZyXinpAolGrVfKlWv6BuhH4leVG6Bvg/6Brm13iauHc+YRHx1xepEj'
    'pCFWjCCc0IUXB9EiobkX4whUziXN7X5LSQN/vAjTYAawYoOtVzTYr+gboq1WJfjb1Ev6s+2viO'
    'sSWuGIHV5404XkbLG9zFQdOQv8cwaUpFHMBy30pRXY3dRv6EVOCZx1/eMCpwzOA/1Hwso5mn4H'
    'vp9v/4S4jJHYdBHjNNhl5n8eywsOb3qZu+RzuEJUAKApY0UAGgDcAQAqcMrgfKF/LYY5p6RvAc'
    'CX2zbxtYCPGDkNxoHMQAThfIFTiyeLmQz5+EaU3W6k6E2QIhVpnbxpAk3vEpqCds7ldBo92Ckg'
    '4zC33kKW+S2mpgRkW0jNExzSGo7kLkrgU1xItYL+XRzZR+KWWvGRfQLUt6CdryvXFeeDAkcDp6'
    'J/WOCUwdlAwbFNTb8PDw9yD5paV/Q7yoOmPNDKg5Z7oJUHLfdAKw9a7oFWHkr6Z1zSuQfOwWer'
    'GErKw0PYu6O01bpyQ3FuFjgaOLf02wVOGZwqrLDNsr6Tty21gvTOKoay8rALe/eVtlpX1hRHFD'
    'jXwVnXNwscDZyqvl3glMH5VL83vKF6yIH4a1X8t2lUvf1Ov659IK6rlt28EB+hHb3bz5tC7fZ5'
    '2dd+uTNBYS2GDUjuTaKpF06u3EBsLpPM2z817btS+ajf/GPp3lFmsb+cEKcowp+F0ZvQZfkXv9'
    'tEj7+HZB3ouvjbBnr8PdXj/7JB/WVfbC7GY3Q+ekKZsZ2ERl7q4QqkMvbPAUP1nZmXisJg2H/6'
    '9Me5Almh36D3zIPzNJ0nz/b2RvJCTiNuscsscJjL5vxkmIHYE4JsOQr4Og4X3KHV1UNX5d6fzx'
    'PmDIPQiy8VrqSe3Ui0Rv6PFsA5i0a4y77HFnBPY/QTGc+ClHs7fF4EIxBqvvBlH0e4uW+4p/q4'
    '4EE+GGIJOzJ9Bkj8+/wdYKrlFifcbIFGjUbm5VPKG2LeYSvPmCCMAPTwejYbpzDFFooew9E7cO'
    'DPn3ro4eh37wEBZ4VcLEEgxtECwFY4xBWQ/wuHWM7gUeSr1ugtD2kP+VczjlApMg7QHK9SrQ4I'
    'm4KK6FdBdWWgNNlw6M3UC6JYW2F0tafyHqQJRxRmpvAcgdPL1fzF7MIsA1dyUQDELEp5onBOUJ'
    '14fGDejWiMDbF8qYzTN1wmeQVRMpc+VxC0Ai6smGsnzKooSRR2Qe6x5ZDTO3RPDdsk0H2799Jq'
    'm21qnmHTpFavf2ZbR8cuHfc6bdN2yOi2we26ttUcuD3bEVQzHKjW1I7RPSPzF33bdBzq2WSd9D'
    'sWrMG8bXRdy3TqZHVbnUHb6h7VCRao23MF3kMnlgs5t1dXbr+vR71DOjHt1jGWRtPqWO6Zcnho'
    'uV12dtizBRnUN2zXag06hk39gd3v4Y3FkbUtp9UxrBOz3YB/+CTzpdl1yTk2Op23AxXUO+2aNq'
    'MvhklNEyiNZsdkVyrOtmWbLZcDuqJaSB4AduqCnL7ZskAhHybCMeyzem7UMX8+gBQ2qW2cGEeI'
    'bvd/ZQUH0xrY5gmjRiqcQdNxLXfgmnTU67VVsh3Tfol3pfOcOj1HJWzgmADSNlxDuYYNpAv7oJ'
    'sDx1KJs7quaduDvmv1uo9xyqfIDFAa0G2rDPe6HC3Xitmzz9gs50GdQJ1Oj03wbU6qypbBaXCQ'
    'tZZbFINDJBEhXcVJXfOoYx2Z3ZbJ2z02c2o55mMcmOWwgKUcowbgdKCi5oMCLpHRhdKtq/Mk65'
    'CM9kuLkefSqADHystFpa11nOc8f8gSpskWqIpeA/WcmZVHOc1cfgn8VHHXc5q5D0HVFVfLaeY+'
    'AvWF4i5ppn4Iqqa4IqeZy/P/geI+zGnm7oK6r7j3c/pfJfWoOsBC3/5HCSU+kSGuv09qkqK/J4'
    'k3kdkouIwW6hkfyyc8cNBFvIsoGGWfFKoNLuZTHipyJN7WV20Y6jEZfYs/jQjjGpLT5ScCv5xh'
    'T80xvCazN2acfZ4Jyrvb8vORlVULBBbY4yF0Ho0a6pODPya80JfLqbT8MDiMIvomYxHFc5+aXr'
    'z7Hz8fH68e2+/Zf56Z+ZYbHFC9cFDCPFEw05ftnj9DXinpVxxZlgslGA1/Lf2UXn3z7Sv13ZE9'
    'Yg/wPLu5fEb9G3qTMik=')))
_INDEX = {
    f.name: {
      'descriptor': f,
      'services': {s.name: s for s in f.service},
    }
    for f in FILE_DESCRIPTOR_SET.file
}


TestServiceDescription = {
  'file_descriptor_set': FILE_DESCRIPTOR_SET,
  'file_descriptor': _INDEX[u'test.proto']['descriptor'],
  'service_descriptor': _INDEX[u'test.proto']['services'][u'Test'],
}
