# Generated by the pRPC protocol buffer compiler plugin.  DO NOT EDIT!
# source: isolated.proto

import base64
import zlib

from google.protobuf import descriptor_pb2

# Includes description of the isolated.proto and all of its transitive
# dependencies. Includes source code info.
FILE_DESCRIPTOR_SET = descriptor_pb2.FileDescriptorSet()
FILE_DESCRIPTOR_SET.ParseFromString(zlib.decompress(base64.b64decode(
    'eJylWjtwG0l6XgB8QCNKO4K0Kx61jz7qKAE6PPiQtBK1DkAQJEcHAjwMIJ2k2pIGQIOcW2AGxg'
    'xIUVp5o3PkcubQ5SoHDi63c6cuJ06cOHXgcuzAob//n57BkCudrs4satnzTff/6r//R89qv1vS'
    'LtueO7B82SuOxq7vZtLh89LXh657OJAlxjuTfsm3h9LzreEomLr8NwltwfQt32vKP5/gTWZdm6'
    'Olnr+YEInsxfWlYkCiGJIotkISTTUzc1fTxhIsJ77tOotJrLu8fq0YCdWM3jVj8zI3tAsj61C+'
    '9Ow3cjGFRbPNNAEmnpdr2iUlljdyHU9mHmkLQ2l5k7EcSsf3IF0K0l2fcuHppmONvCPXb56ZvP'
    'xvSUUufJ+5oyWZyMdUxKzMojY/GQ1cq+exbqlm+Ji5qV1Sw5edU5iC1Ug1FxS4RVjmC+1Czz1x'
    'AgIzPGEKZG5rn0YPisgsz7kcwQGZX2pXuq7jW7bjvRwHm+UtzvFUPXyhNtHL5LQIezlw3e8nI2'
    '9xnud+GuK1AM4saemIXJqnRM/0rm/ZA9jRW7wQvAuf7+xq2nRjMfPzZtVs1Noto1F/2a6bB9WK'
    'sWNUt/VPMpo2t2/U262qnsiktZm9RrupJzPzWmq7/ExPre9oaUNtYmZTm+V9ynx+bmOVZkvnNz'
    'z0j+VPHv/PVS2tz+if6A/1hPaPifQCP2TWf58QFXd0OrYPj3yxvrr2QLSOpKi1K4YoT/wjd+wV'
    'RXkwEDzBE9BNjo9BXxNtTwq3L/wj2xOeOxl3pei6PSnweOgey7Eje2Li9OQYU6Qoj6wuEba7Eg'
    'LlxRM59mAasV5c1TDB8kXXckRHir6LRcJ2eFXNqFTrZlX0bTigpqXTSX1OT+s6hqn0JxjN61lt'
    'IT2HsQZ1LkE3fkon8EzzXvBTEu8X9KR+d+lXgg0DPfzJ2IHgeLI93+56YDwOlKEoIMaWcygFxC'
    'Ix1JZDoekJhTh6SBzsFiDYxRiSBLKgL8aQFJ5v6qvat+lZiKND3M/0xFJRTP1E+K6YeJIlMWFm'
    '2KoYissCgOcCrQY/XZ/VP9Uu8xOpdwXqfQlus5FEhCzGkCSQG/oX0ZqEnsGMS9GMhELSMSQJ5K'
    'K+EK1J6lcx42I0g6gQMhdDaM4F7FC4JqVfwwwtmpHCGkJmY0gSSFq/AO1moMt12EbwVs6wJtfx'
    '7pr2Hwl+JGVvYPntpX9JiCDEksvRNg0sjBHSxqdkSfiSN5Jdu2/LyJ9COwqjLxzXn07IayGtnu'
    'xbkwFsDhK0pDsZj0GTvYLX/RBM/IG5ui5odul98Edj/rb0xImNUwMZhrbn2c6hsFjGU2GNJbM+'
    'lXB5dzia0GnVtEyoXHqG1buufw77hNgcYzdiSIL2Ul+OISkgK/ot7bZCEvqXWPPF0nXRfL/7hi'
    'xhV556Q78dkUuAJWELMYQIXtKvx5AUkCWIta2QpP411ny+dFfsW6/t4WQonMmwgwiAOHEmw0RW'
    '8l11FGPyJCEP0fkSzqpH2Cxj8zEkASStX4khKSDX9M/YcRL6MtzolnKjBD+n8e5vE/xIbrQCgn'
    'eW/irBsqko4IUSwmPGEmEM57F7NHYdd+Ae2l1rINwxYhp2tEiREpup4taRO5CeFjraAOQe0Wgs'
    'b3vCglcNrFNMw9GWoceENiCP6I6lFTiCHooHK6yogxMic0Au8qEOkQSQn+krMSQFJKvntE0gST'
    '0XRPyl/Dn7h3lOeEGciQVCDjIzbN8cW+wyP5HB7kCem7xPSSUhITnlE0kl453IVZNKxjtw1a9i'
    'SArIz+G8IeWEnseaaxFl8khC7oCbHmGzjM3HEFqXRhicIikgGf1qRDmpF7BmKaJMvkVIHtz0CJ'
    'tlbD6GJICQ7lMkBWRR/1lEOaUXydcjyilQJqQAbnqEzTI2H0MSQEKvDRCidC1m5xm9RAc3ojyj'
    'kKIKCQE2y9h8DEkAScf2YgaUS3w+TYXM6utY89VSRdSjc1mKXCEsbISFBOy7Pnx9enxtXw49Qd'
    'USpfWROq5MFOIR2ZI6rgEWsJqPIQkgaRhwiqSAfIGsFSo+p29wFgspz4EyIesx55kD5Y0zlOdA'
    'eQOUF2NICgjlum8VMq/fx5rPcAxa5/SKlEYkwunuTii6i18fmDEN5yEHrd/gDBtis4zNx5AEEC'
    'o6pkgKyFW4WkEhaf0By/FlbAMc1ymsr65GksQYp8GYFtyPeWIajB+cYZwG4wdnGKfB+AEx7sxx'
    '1b6h/WdJ+1i3k/n0XKG//Ei7ENX6VOd7Er7SCxoD1PnqMXNNm3Usxw3q/9lm8LD1F9pVpLfzzc'
    'PW5YjiAUEHiee/PLT9o0mniNmlQ1SvzuFUxJF/OpLeVNL/TST+PpnaPdj6ffKr3YDyQdiWPJWD'
    'wa8ctAUtWvP4vwvaBf0rhL+/TCAH/OsCKt6vuOL95wXBa7ruQGxN+n2EeFEQATXE6p7lW4jivh'
    'x3j7gGRMgeWkjs8TJ59YFaIAynWxQfqJCPfH/kbZZKPeSRgTsCo9AcpOtICVHoBEKUNA2Zuocg'
    'PLY7QT1IB5EKQiQVVWET0rEdCyUOyeXlUWf4R8hJ/NedQM6h20NJ07WIQp6TCzgPbZ/yP3ge2z'
    '0MuOKmRNV3BwP3hAoU2kybFnFGAh3pb0Ik+rlzTjCP/DZe8w8nHlVAFEeYqtVBB4BXymIaVTzI'
    'MvmgwKbkSBTiHCnknBEH/LoDCxs/Ln5ICDCL2SIUAjr2JhAskkObCvL/kiNK7j23O6HW2Qo3qQ'
    'T7u5TsBTwFxYE18Kam5g3CS03EpY+UqkubVxJhxxpyTxX3LcedvvOCSOxpnL+ZFBo0MKXSgjyF'
    '4jbqip5LZQsWQoihi3gW2ATeSaULnFP08UILe7e+f0JuojwoLIq7WGWTY43Jd5zAizwvqB1Fa8'
    '8whdnYaT0tN6sC44Nm44mxXd0WW8/wsioqjYNnTWN3ryX2GrXtatMU5fo20HqraWy1W42mqYnl'
    'somly/ymXH8mqr85QJ9sikZTGPsHNTTIAuSb5XrLqJp5YdQrtfa2Ud/NC1AQ9UZLQ4e4b7Qwr9'
    'XIM9ufrhONHbFfbVb28FjeMmpG6xkz3DFadWK202hqoiwOys2WUWnXyk1x0G4eNNB1kmbbhlmp'
    'lY396jaK/zp4iuqTar0lzL1yrXZWUU00ntarTZI+rqbYqkLK8latSqxYz22jWa20SKHpqALjQc'
    'AaOhG+HsAI9qhCnXLzWV4RNau/bmMWXort8n55F9plP2YVbEyl3azuk9QwhdneMltGq92qit1G'
    'Y5uNbVabT9Bpm49ErWGywdpmFYJsl1tlZg0aMBfeY7zVNg02nFFvVZvN9gFdauSwy09hGUhZxt'
    'pttnCjTtqSr1QbzWdEluzAO5AXT/eqwJtkVLZWmcxgwmqVVnwaGMKIUGmqp6hXd2vGbrVeqdLr'
    'BpF5apjVHDbMMGmCwYzhA2DaZq1poyCXFoxjrpvn/RTGjihvPzFIcjUbHmAayl3YbJU9ZXN1ES'
    'G42EKu5UbjEYHpFTUm9CZGXzP6tRoT+guMthi9qMaErmCUZzShxoTewqjEaDim0W2MlhnV1JjQ'
    'LEY/Z/QXavxPN7iZfqNS4NI/3ICXR9mXAyVSlUP1nhi5yHgc3ujuw3Z6coQoQk0KAo7lnAb4G9'
    'dBFENIQKGE19Y4P6WCmGJRN8ElAYfR/tjqTpNF+IJyAdUH/BzrR4l5u1UR1ZHbPQqbbe7spUMp'
    'hhIhhWMOpMjfAzlCJBe7Y3noIuA6oqJkEidHNijI14hZveBeYDopFFwTHav7PaJejwu/U4l1UO'
    '48S8vzJkNu3pHfMUCvHrRr91e1SKWB6xzmhV3E6oG0RlNVMW/ZG4K07C0jygY513HjsxCCrc6A'
    '78wcKYkl3f1w9TGidMqZQjS5DsGcIGqvrq6uFfi3tbq6yb/PSYuH+CmsrRc21lrrG5v3HuK3+D'
    'D8eY6Es3VKBkfewL6QKZVIfNWFQkJCb7oVDtCToLOFlGiCUSu4mtpVdyhEc6ciNjY2HlK1RL0j'
    '9cMoXIUppXgRlj0nJydFW/r9ojs+LI37XfpHi4r+a/+77B8zK0eZ5qaovobDUnethUOxtol6jC'
    '9PYi7NsuHcGr8Rr8iDsrlXRVXBTCdFteSj4M20Cvak/1JtXpaX19u1Wi733nnsw9lVvJzKtP4x'
    'mQ6lT1Tcfs86jckG8yE3M4Nj9Cb+seJ4Zvot/zgvWKBHf6pKx0X/mJ7+kEbBJFQSXZQma/C0Mx'
    'pufFDDp7azsS5e7UrfPPXQKtLrsrdjD2Tr7EbsGLVqC+lU9H0lxofW3Or7oaRtpJr7dyFw93tP'
    '/JnIZrMBkuv7xd7JHiq7bfghrcqJb78VG+s58YPgdzX3JHwV2q1UQhyEvD33xGOSdLKgaiwuec'
    'VoguR4tHb/p0cuokbL1+7fvXv3m437IBOef3XZ03bs1yGVh9+snqdS/NM2MxvoD1MERinxZtFP'
    'Ds1MTJyPeDDRIXOFdFZidNgBcmcc4O4HHeCxdWyJV8FGFtWdKU3Ztwcos2MOQOESsZRQbOWHF/'
    'wBN8e6CC068mRrYg9Q2GZzpJipLKRYBIbJBbToh+bUA90RZ0lzNTNQXanNFsgVO0SZZZna4N4H'
    'bRC/KqZ8dnCKgtoJFX+v+Nnc+b3BcahMrYH3FAEfm6il9q3RCHEWgOEESNCa5jnJxeyE/vdsFk'
    'OGD2K06mA08SKM4H9kIFas6M7TohSZD8gEKDFbfktJ9F3h7RCdyRH+Imi9a71FQzF+t/kWuRP/'
    'hfO+e1F8S4UBOfK7754va0jXdIkarCZC1uDEOoXwr6mw8KK83wchNFCH6H4ow2MfFKe8YFaoVg'
    'NmeCZuec5WzJIz8Rs5dgsjq9cLeiT/xA2pSat7xHe5UcViDaLsnlflBKXCQ1dMRpxow6VZzvoB'
    'uPb+uiYHwYi/OwooB5yWn6MiQNuP0IA4Q826DEoV8gMqs0R2GdXQcu7RGVQjA9E9kY2aoogwFt'
    'zuBM7gceNpQ1HhwRKDXmhKukGg0ipreRG3nuicaiRGjjbAoVbP8VV9dd6VyJDWGVYjC/1lxKYD'
    'ubiKgRWsbheFmeigG2aetDbojEMdvJ/IgUkoEfs4l5zvd1AByeCs5cXy+uraNxQz1+61Vtc2N1'
    'Y31+4VV9dgvsC7EXrpOQq6I8tDhckzmT8Ky8eWM6E7grV7efrA+U1RHSAELLM7tkc4P2TweLFj'
    'CUoawu38VlJidoNGWTl7rA6Fkaia7IkXvmuYDZPPWDY3PVPRzU9x6L5BmLH4cEmn0DZLPbfrlZ'
    '7KTmkqSakp+zgNTleWdgduxxq8bLAIXonkKcWYfMf3M0cuvMAIA02ej7mS6BVVZlxGh4NXoT7q'
    'g4VSVlIR+j4NX7xCzOjzyphCELo4CuIaqbJeGtidMczLd3TFI384uMmjcC3iW3gBEsRFxYMuGc'
    'TtlWeFlWFhpdda2dtc2d9cMYsr/ee3i6Jmfy9PbPpObAc7xXuksejkzkTtsduz2FVve5AVlgkT'
    '/U4QqnrqEbnnu2xwGaei3G+xkqWnQYGkKlkjm/cjRFmdUiBr6ae0Wc+QQaGgiRzZ0O3wBZildE'
    'QRD4FHfDTQAh1KR46t4JCFB8wLAnJkevimFn32fMPfCf5u+tnzR/pIsvTXCdGc9m6h44MB+Tub'
    'GNvXjRce2vsrD7FPF2b0yZ2S1we6Cu19bcVziN0dwE2O5blPlyTiG/1q7LPkLGPzMSQBJPxqE3'
    '66/JG/2vxXqGtC/10CqzJL/54QddcpOPIQljuWZ5tKS2lPn+nfG3yLoq4WhgFdoMKe8NdZ+OSU'
    'GF8dej59sj2yjiXfyUc8mbRaGP6/Cu4EeR57Ri1k2DefN6jqyfLqn3bGaFdjH19Z1x/1a9qVCJ'
    'wNwPkYxDZJ65diUIogXb8SXvP/H/XG5VU=')))
_INDEX = {
    f.name: {
      'descriptor': f,
      'services': {s.name: s for s in f.service},
    }
    for f in FILE_DESCRIPTOR_SET.file
}


IsolatedServiceDescription = {
  'file_descriptor_set': FILE_DESCRIPTOR_SET,
  'file_descriptor': _INDEX[u'isolated.proto']['descriptor'],
  'service_descriptor': _INDEX[u'isolated.proto']['services'][u'Isolated'],
}
