# Generated by the pRPC protocol buffer compiler plugin.  DO NOT EDIT!
# source: isolated.proto

import base64
import zlib

from google.protobuf import descriptor_pb2

# Includes description of the isolated.proto and all of its transitive
# dependencies. Includes source code info.
FILE_DESCRIPTOR_SET = descriptor_pb2.FileDescriptorSet()
FILE_DESCRIPTOR_SET.ParseFromString(zlib.decompress(base64.b64decode(
    'eJylWjtwG0l6FgA+oBGlHUFaLY/SafuoowhIIAA+JJ2odQCCIDk6EODhIZ2k2pIGQIOcW2AGxg'
    'xIUVp5o3PkcubQ5SoHDi735Ze6nDhx4tSBy7EDh/7+f3oGQ650ujqzqGXPN93/q//+Hz2r/XZB'
    'u2K5Tt/0ZDc3HDmek0oGzwtfHzrOYV/mGW+Pe3nPGkjXMwdDf+ri38W0uYZnem5d/uUYb1Jr2g'
    'wtdb35mIilL60t5HwSuYBErhmQqKuZqQ1NG0mwHHuWY8/Hse7K2vVcKFQ9fFePzEvd1C4OzUP5'
    '2rXeyfkEFk3XkwQ08LxY0S4rsdyhY7sy9USbG0jTHY/kQNqeC+kSkO6rCRee3rDNoXvkePUzkx'
    'f/La7IBe9T97Q4E/mcipiVmtdmx8O+Y3Zd1i1RDx5Td7TLavi6fQpTsBqJ+pwCtwhL3dIudp0T'
    '2ycwxRMmQGpZ+yJ8UESmec6VEPbJ3NeudhzbMy3bfT3yN8udn+GpevBCbaKbymgh9rrvON+Nh+'
    '78LM/9IsArPpxa0JIhuSRPCZ/pXc+0+rCjO3/Rfxc839vVtMnGYuaNerlRq7SaRq36ulVtHJRL'
    'xo5R3tYvpDRtZt+otpplPZZKalN7tVZdj6dmtcR28YWeWNvRkobaxNSmNs37lLpxbmOVZgvnNz'
    'zwj8ULT//nmpbUp/QL+qYe0/45lpzjh9Ta72Ki5AxPR9bhkSfWCqu/EM0jKSqtkiGKY+/IGbk5'
    'Uez3BU9wBXSTo2PQ10TLlcLpCe/IcoXrjEcdKTpOVwo8HjrHcmTLrhjbXTnCFCmKQ7NDhK2OhE'
    'BZ8UyOXJhGrOUKGiaYnuiYtmhL0XOwSFg2r6oYpXK1URY9Cw6oaclkXJ/Rk7qOYSJ5AaNZPa3N'
    'JWcw1qDOFejGT8kYnmneK36K4/2cHtc3Fn4p2DDQwxuPbAiOJ8v1rI4LxiNfGYoCYmTah1JALB'
    'JDbTkUmpxQiKMHxMFuDoJdiiBxIHP6fARJ4PmOXtC+SU5DnKsQ94YeW8iJiZ8IzxFjV7IkDZgZ'
    'tsoF4rIA4DlHq8Hvqj6tf6Fd4SdSLwX1fgpu06FEhMxHkDiQm/qtcE1Mv4YZl8MZMYUkI0gcyC'
    'V9LlwT169jxqVwBlEhZCaC0JyL2KFgTUL/EjO0cEYCawiZjiBxIEn9IrSbgi7zsM3PeCunWJN5'
    'vLuu/UeMH0nZW1i+vPAvMeGHWHI52qa+iTFC2uiULAlfcoeyY/UsGfpTYEdh9ITteJMJWS2g1Z'
    'U9c9yHzUGClnTGoxFoslfwuu/9id8zV8cBzQ699/9ozN+SrjixcGogw8ByXcs+FCbLeCrMkWTW'
    'pxIu7wyGYzqtmpYKlEtOsXrz+g3YJ8BmGLsZQWJAbumLESSB5yX9rraskJh+G2tuLXwl6h9334'
    'Al7OpP1ZdDcjGwJGwughDBy/pXESQBZAFibSskrgusubGwIfbNt9ZgPBD2eNBGBECcOJNhQit5'
    'jjqKEXnikIfo3Iaz6iE2zdhsBIkBSepXI0gCyHX9S3acGA7bBX1ZuVGMn5N49/cxfiQ3uguC9x'
    'b+JsayqSjgBhLCY0YSYQznsXM0cmyn7xxaHbMvnBFiGnY0R5ESm6ni1pHTl64WOFof5J7QaCSX'
    'XWHCq/rmKabhaMvAYwIbkEd0RtL0HUEPxIMV7qqDEyAzQC7xoQ6QGJCf6EsRJAEkrWe0TSBQz4'
    '/4C9lz9g/ynHD9OBMJhBxkpti+99hiV/iJDHYf8tzhfYorCQm5p3wirmS8H7pqXMl4H751O4Ik'
    'gPwMzhtQjukrWHM9pEweSch9cNNDbJqx2QhC65IIgxMkASSlXwspx/Uc1iyElMm3CFkBNz3Eph'
    'mbjSAxIKT7BEkAmdd/ElJO6Hny9ZByApQJyYGbHmLTjM1GkBiQwGt9hChdj9h5Si/QaQwpTykk'
    'r0KCj00zNhtBYkCSkb2YAuUCn8+GQqb1dTpXCyVRDc9lPnSFoLARJhKw53jw9cnxtTw5cAVVS5'
    'TWh+q4MlGIR2QL6rj6mM9qNoLEgCRhwAmSAHILWStQfEbf4CwWUJ4BZULWI84zA8obZyjPgPIG'
    'KM9HkAQQynXfKGRWf4Q1X+IYNM/pFSqNSITT3RlTdBe/OmhENJyFHLR+gzNsgE0zNhtBYkCo6J'
    'ggCSDX4GorCknqj1mOn0Y2wHbslbVCIZQkwjgJxrTgUcQTk2D8+AzjJBg/PsM4CcaPiXF7hqv2'
    'de0/89rnup3UF+cK/cUn2sWw1qc635Xwla7fGKDOV4+p69q0bdqOX/9P1/2Hrb/SriG9nW8etq'
    '6EFA8IOoi9vH9oeUfjdg6z84eoXu3DiYhD73Qo3Ymk/xuL/WM8sXuw9bv47V2f8kHQljyX/f4v'
    'bbQFTVrz9L9XtItIIRf0v44hB/zrHCre21zx/mFO8JqO0xdb414PIV6sCJ8aYnXX9ExEcU+OOk'
    'dcAyJkD0wk9miZXPiFWiAMu5MTn6iQjzxv6G7m813kkb4zBKPAHKTrUAmx0vaFyGsaMnUXQXhk'
    'tf16kA4iFYRIKqrCJqRt2SZKHJLLzaLO8I6Qk/ivM4acA6eLkqZjEoUsJxdwHlge5X/wPLa6GH'
    'DFTYmq5/T7zgkVKLSZFi3ijAQ60tuESPRz75xgLvlttOYfjF2qgCiOMFWzjQ4Ar5TFNKp4kGWy'
    'foFNyZEoRDlSyDkjDvh1+iY2fpT7lBBgFrFFIAR07I4hWCiHNhHk/yVHmNy7TmdMrbMZbFIe9n'
    'co2Qt4CooDs+9OTM0bhJeaiEofKlWVFq8kwrY54J4q6lu2M3nn+pHY1Th/Myk0aGBKpQV5CsVt'
    '1BVdh8oWLIQQAwfxzLcJvJNKFzin6OGFFvRuPe+E3ER5UFAUd7DKIscake/Yvhe5rl87iuae0R'
    'CN2k7zebFeFhgf1GvPjO3ytth6gZdlUaodvKgbu3tNsVerbJfrDVGsbgOtNuvGVqtZqzc0sVhs'
    'YOkivylWX4jyrw/QJzdErS6M/YMKGmQB8vVitWmUG1lhVEuV1rZR3c0KUBDVWlNDh7hvNDGvWc'
    'sy2x+vE7UdsV+ul/bwWNwyKkbzBTPcMZpVYrZTq2uiKA6K9aZRalWKdXHQqh/U0HWSZttGo1Qp'
    'GvvlbRT/VfAU5WflalM09oqVyllFNVF7Xi3XSfqommKrDCmLW5UysWI9t416udQkhSajEowHAS'
    'voRPh6ACPYowx1ivUXWUW0Uf5VC7PwUmwX94u70C79OatgY0qtenmfpIYpGq2tRtNotpplsVur'
    'bbOxG+X6M3TajSeiUmuwwVqNMgTZLjaLzBo0YC68x3ir1TDYcEa1Wa7XWwd0qZHBLj+HZSBlEW'
    'u32cK1KmlLvlKu1V8QWbID70BWPN8rA6+TUdlaRTJDA1YrNaPTwBBGhEoTPUW1vFsxdsvVUple'
    '14jMc6NRzmDDjAZNMJgxfABMW6w1bRTk0vxxxHWzvJ/C2BHF7WcGSa5mwwMahnIXNltpT9lcXU'
    'QILraQa/VF5JUnBCaX1JhQaj++ZvRrNSb05xhtMXpJjQldwijLaEyNCb2LUZ7RYEyjZYwWGdXU'
    'mNA09cyM/lyNf3+Tm+l3KgUu/NNNeHmYfTlQIlXZVO+JoYOMx+GN7j4suyuHiCLUpCDgmPapj7'
    '9zbEQxhAQUSnhtjrITKogpJnUTXBJwGO2NzM4kWQQvKBdQfcDPkX6UmLeaJVEeOp2joNnmzl7a'
    'lGIoEVI45kCK/N2XQ0RysTuShw4Cri1KSiZxcmSBgnyLmNX17wUmkwLBNdE2O98h6nW58DuVWA'
    'flzrM0XXc84OYd+R0D9Op+u/awoIUq9R37MCusHFb3pTmcqIp5i+4ApGV3EVHWz7m2E52FEGy2'
    '+3xnZktJLOnuh6uPIaVTzhSiznUI5vhRu1AorK7wb7NQ2OTfl6TFY/ysrK6trK8219Y3HzzGb+'
    '5x8PMSCWfrlAyOvIF9IVMqkfiqC4WEhN50K+yjJ35nCynRBKNWcDS1q85AiPpOSayvrz+maol6'
    'R+qHUbiKhpTiVVD2nJyc5Czp9XLO6DA/6nXoHy3KeW+9b9N/yqwMZZo7ovwWDkvdtRYMxeom6j'
    'G+PIm4NMuGc2v8WrwhD0pn3uRUBTOZFNaST/w3kyrYld5rtXlpXl5tVSqZzEfnsQ+nC3g5kWnt'
    'czIdSo+oOL2ueRqRDeZDbmYGx+hNvGPF8cz0u95xVrBAT/5clY5z3jE9/TGN/EmoJDooTVbhaW'
    'c0XP+khs8te31NvNmVXuPURatIr4vujtWXzbMbsWNUyk2kU9HzlBifWnO35wWStpBqHm5A4M53'
    'rvgLkU6nfSTT83Ldkz1UdtvwQ1qVEd98I9bXMuJ7we8qzknwKrBbPo84CHm7zonLJOlkQdVIXH'
    'Jz4QTJ8Wj14Y+PXEiNlq8+3NjYeLT+EGSC868ue1q29Tag8vhR4TyV3J+3mWlff5jCN0qeN4t+'
    'MmhmIuJ8xoOJDpkroLMUocMOkDnjABufdICn5rEp3vgbmVN3pjRl3+qjzI44AIVLxFJCsZWfXv'
    'BH3BzrQjRny5OtsdVHYZvOkGINZSHFwjdMxqdFPzSn6uuOOEuaq5m+6kpttkAm1ybKLMvEBg8+'
    'aYPoVTHls4NTFNR2oPhHxU9nzu8NjkNpYg28pwj4tIFaat8cDhFnARi2j/itaZaTXMRO6H/PZj'
    'FkeD9Gqw5GE6+CCP4nBmLFiu48TUqRWZ+MjxKzxfeURD+svB+gMznCXwStD833aChGHzbfI3fi'
    'v3DeD69y76kwIEf+8O3LRQ3pmi5R/dVEyOyfmKcQ/i0VFm6Y93sghAbqEN0PZXjsg+KUFcwK1a'
    'rPDM/ELcvZillyJn4nR87K0Ox2/R7JO3ECatLsHPFdblixmP0wu2dVOUGp8NAR4yEn2mBpmrO+'
    'D65+vK7JQDDi7wx9yj6nxZeoCND2IzQgzlCzLv1ShfyAyiyRXkQ1tJh5cgbVyEB0T2ShpsghjP'
    'm3O74zuNx4WlBUuLBEvxuYkm4QqLRKm27IrSvapxqJkaENsKnVsz1VX513JTKkeYbV0ER/GbJp'
    'Qy6uYmAFs9NBYSba6IaZJ631O+NAB/dHcmASSsQeziXn+x1UQNI/a1mxuFZYfUQxc/VBs7C6uV'
    '7YXH2QK6zCfL53I/TScxh0h6aLCpNnMn8Ulk9Ne0x3BKsPsvSB81FOHSAErEZnZA1xfsjg0WLH'
    'FJQ0hNP+jaTE7PiNsnL2SB0KI1E12RWvPMdo1Bp8xtKZyZkKb35yA+cdwozJh0vaK61Gvut03P'
    'xz2c5PJMnXZQ+nwe7I/G7faZv91zUWwc2TPPkIk2/5fubIgRcYQaDJ8jFXEr2hyozL6GDwJtBH'
    'fbBQykoqQj+m4as3iBk9XhlRCELnhn5cI1XW8n2rPYJ5+Y4ud+QN+nd4FKxFfAsuQPy4qHjQJY'
    'NYXnqxsjRYWeo2l/Y2l/Y3lxq5pd7L5ZyoWN/JE4u+E1v+TvEeaSw6uTNRe+p0TXbVZReywjJB'
    'ot/xQ1VXPSL3fJv2L+NUlPsNVrL0NFghqfLm0OL9CFBWJ+/Lmv8xbdYzYLCyookM2dBp8wWYqX'
    'REEQ+Bh3w00AIdSluOTP+QBQfM9QNyaHr4phZ+9nzH3wn+YfLZ8wf6SLLwtzFRn/RugeODAfk7'
    'mxjb14kWHtrHKw+xTxdm9MmdktcnugrtY23FS4jd6cNNjuW5T5ck4jv9WuSz5DRjsxEkBiT4ah'
    'N8uvyBv9r8V6BrTP9tDKtSC/8eE1XHXrHlISx3LM82labSnj7TfzT45kRVLQwCukCFPeavs/DJ'
    'CTG+OnQ9+mR7ZB5LvpMPeTJptTD4fxWcMfI89oxayKBvPm9Q1ZNl1T/tjNGuRT6+sq4/6Ne1qy'
    'E47YOzEYhtktQvR6AEQbp+Nbjm/z85ueW8')))
_INDEX = {
    f.name: {
      'descriptor': f,
      'services': {s.name: s for s in f.service},
    }
    for f in FILE_DESCRIPTOR_SET.file
}


IsolatedServiceDescription = {
  'file_descriptor_set': FILE_DESCRIPTOR_SET,
  'file_descriptor': _INDEX[u'isolated.proto']['descriptor'],
  'service_descriptor': _INDEX[u'isolated.proto']['services'][u'Isolated'],
}
