# Copyright 2020 The LUCI Authors. All rights reserved.
# Use of this source code is governed under the Apache License, Version 2.0
# that can be found in the LICENSE file.

# Feel free to run `make deploy` anytime you want to deploy head to dev.
# Notify owners if you want to deploy your local change.
deploy:
	./tools/gae upload -x -A isolateserver-dev
